config/routes.rb
Rails.application.routes.draw do
  resources :customers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current_machine.rb
class CurrentMachine < Machine

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one :current_machines, inverse_of: :customer, dependent: :destroy
  has_many :old_machines, inverse_of: :customer, dependent: :destroy

end

app/models/machine.rb
class Machine < ApplicationRecord
  belongs_to :customer, inverse_of: :machines
end

app/models/old_machine.rb
class OldMachine < Machine
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/current_machines_controller.rb
class CurrentMachinesController < ApplicationController

  def index
  end

  def show
  end

  def new
    
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
 
 def index
   @customers = Customer.all
   @current_mac = CurrentMachine.all
 end

 def show
   @customer = Customer.find(params[:id])
 end

 def new
   @customer = Customer.new
 end

 def create
   @customer = Customer.new(customers_params)
   if @customer.save
     flash.notice = 'Made New customer'
     redirect_to :customers
   else
     render action: 'new'
   end
 end

 def edit
   @customer = Customer.find(params[:id])
 end

 def update
   @customer = Customer.find(params[:id])
   @customer.assign_attributes(customers_params)
   if @customer.save
     flash.notice = 'Update info of customer.'
     redirect_to :customer
   else
     render action: 'edit'
   end
 end

 def destroy
   customer = Customer.find(params[:id])
   customer.destroy!
   flash.notice = 'Erase customer'
   redirect_to :customers
 end

  private

  def customers_params
    params.require(:customer).permit(:name, :deposit,
     current_machines_attributes: [:current_mac, :start_current_mac, :broken])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<div>
  <div>
    <%= f.label :name, 'name' %>
    <%= f.text_field :name, size: 32 %>
  </div>

  <div>
    <%= f.label :deposit, 'deposit' %>
    <%= f.text_field :deposit, size: 32%>
  </div>
</div>

app/views/customers/_machine_form.html.erb
<div>
  <div>
    <%= mac.label :current_mac, 'MAC NUMBER' %>
    <%= mac.text_field :current_mac, size: 32 %>
  </div>

  <div>
    <%= mac.label :start_current_mac, 'Setup machine Date'%>
    <%= mac.text_field :start_current_mac %>
  </div>
</div>

app/views/customers/edit.html.erb
<div>Edit Customer</div>

<%= form_for @customer do |f| %>
  <%= render 'form', f: f %>

  <div class="buttons">
    <%= f.submit 'submit' %>
    <%= link_to 'cansel', :customers %>
  </div>
<% end %>
~            

app/views/customers/index.html.erb
<h1>All Customer</h1>


<table>
  <tr>
    <th>name</th>
    <th>deposit</th>
    <th>create day</th>
    <th>Current Machine</th>
    <th>Other</th>
  </tr>
    <% @customers.each do |customer| %>
  <tr>
    <td><%= customer.name %></td>
    <td><%= customer.deposit %></td>
    <td><%= customer.created_at.strftime("%Y-%m-%d") %></td>
     <% @current_mac.each do |mac| %>
    <td><%= mac.current_mac%></td>
     <% end %>
    <td><%= link_to "show", customer %></td>
    <td><%= link_to "edit", edit_customer_path(customer) %></td>
    <td><%= link_to "Remove", customer, method: :delete, data: { confirm: "Are you sure? "}%></td> 
  </tr>
<% end %>
</table>

app/views/customers/new.html.erb
<%= @customer.errors.full_messages.first if @customer.errors.any? %>
<div>New Customer</div>

<%= form_for @customer do |f| %>
  <%= render 'form', f: f %>

  <%= f.fields_for :machines do |mac| %>
    <%= render 'machine_form', mac: mac %>
  <% end %>
  <div class="buttons">
    <%= f.submit 'submit' %>
    <%= link_to 'cansel', :customers %>
  </div>
<% end %>

app/views/customers/show.html.erb
Customer
<table>
  <tr>
    <th>Name</th>
    <th>Deposit</th>
    <th>Created Day</th>
    <th>Mac Number</th>
    <th>Mac created Day</th>
  </tr>
  <tr>
    <td><%= @customer.name %></td>
    <td><%= @customer.deposit %></td>
    <td><%= @customer.created_at.strftime("%Y-%m-%d")%></td>
     <% @customer.machines.each do |mac| %>
    <td><%= mac.macnumber%></td>
    <td><%= mac.created_at.strftime("%Y-%m-%d") %></td>
      <% end %>
   
  </tr>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Customerlist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>